"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import requests as requests_http
from .llm import Llm
from .manage import Manage
from .profile import Profile
from .sdkconfiguration import SDKConfiguration
from dataservice import utils
from dataservice._hooks import SDKHooks
from dataservice.models import components
from typing import Callable, Dict, Optional, Union

class Dataservice:
    profile: Profile
    llm: Llm
    manage: Manage

    sdk_configuration: SDKConfiguration

    def __init__(self,
                 api_key_header: Union[Optional[str], Callable[[], Optional[str]]] = None,
                 server_idx: int = None,
                 server_url: str = None,
                 url_params: Dict[str, str] = None,
                 client: requests_http.Session = None,
                 retry_config: utils.RetryConfig = None
                 ) -> None:
        """Instantiates the SDK configuring it with the provided parameters.
        
        :param api_key_header: The api_key_header required for authentication
        :type api_key_header: Union[Optional[str], Callable[[], Optional[str]]]
        :param server_idx: The index of the server to use for all operations
        :type server_idx: int
        :param server_url: The server URL to use for all operations
        :type server_url: str
        :param url_params: Parameters to optionally template the server URL with
        :type url_params: Dict[str, str]
        :param client: The requests.Session HTTP client to use for all operations
        :type client: requests_http.Session
        :param retry_config: The utils.RetryConfig to use globally
        :type retry_config: utils.RetryConfig
        """
        if client is None:
            client = requests_http.Session()
        
        if callable(api_key_header):
            def security():
                return components.Security(api_key_header = api_key_header())
        else:
            security = components.Security(api_key_header = api_key_header)
        
        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        self.sdk_configuration = SDKConfiguration(client, security, server_url, server_idx, retry_config=retry_config)

        hooks = SDKHooks()

        current_server_url, *_ = self.sdk_configuration.get_server_details()
        server_url, self.sdk_configuration.client = hooks.sdk_init(current_server_url, self.sdk_configuration.client)
        if current_server_url != server_url:
            self.sdk_configuration.server_url = server_url

        # pylint: disable=protected-access
        self.sdk_configuration._hooks=hooks
       
        self._init_sdks()
    
    def _init_sdks(self):
        self.profile = Profile(self.sdk_configuration)
        self.llm = Llm(self.sdk_configuration)
        self.manage = Manage(self.sdk_configuration)
    