"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ...models.errors import validationresult as errors_validationresult
from .runperf import RunPerf
from dataclasses_json import Undefined, dataclass_json
from dataservice import utils
from typing import List, Optional


@dataclasses.dataclass
class Metrics:
    pass


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class EvaluationResult:
    metrics: List[Metrics] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metrics') }})
    validation_results: errors_validationresult.ValidationResult = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('validation_results') }})
    perf_info: Optional[RunPerf] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('perf_info') }})
    

