"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from dataservice import utils
from typing import Dict, List


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LogEmbeddingRequest:
    dataset_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dataset_id') }})
    timestamp: int = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('timestamp') }})
    embeddings: Dict[str, List[List[float]]] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('embeddings') }})
    

