"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .logmultiple import LogMultiple
from dataclasses_json import Undefined, dataclass_json
from dataservice import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class LogRequest:
    UNSET='__SPEAKEASY_UNSET__'
    dataset_id: str = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('datasetId') }})
    multiple: LogMultiple = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('multiple') }})
    timestamp: Optional[int] = dataclasses.field(default=UNSET, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('timestamp'), 'exclude': lambda f: f is LogRequest.UNSET }})
    

