"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from dataclasses_json import Undefined, dataclass_json
from dataservice import utils
from typing import Dict


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RunPerf:
    metrics_time_sec: Dict[str, float] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metrics_time_sec') }})
    workflow_total_sec: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('workflow_total_sec') }})
    metrics_total_sec: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metrics_total_sec') }})
    validation_total_sec: float = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('validation_total_sec') }})
    

