"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.components import llmvalidaterequest as components_llmvalidaterequest
from ...models.errors import validationresult as errors_validationresult
from typing import Optional


@dataclasses.dataclass
class ValidateLlmRequest:
    llm_validate_request: components_llmvalidaterequest.LLMValidateRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    log: Optional[bool] = dataclasses.field(default=True, metadata={'query_param': { 'field_name': 'log', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class ValidateLlmResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    validation_result: Optional[errors_validationresult.ValidationResult] = dataclasses.field(default=None)
    r"""Successful Response"""
    

